CREATE TABLE users (
	"id" SERIAL PRIMARY KEY,
	"username" VARCHAR(50) UNIQUE NOT NULL,
	"email" VARCHAR(100) UNIQUE NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pains (
	"id" SERIAL PRIMARY KEY,
	"title" VARCHAR(200) NOT NULL,
	"description" TEXT NOT NULL,
	"user_id" INTEGER REFERENCES users("id") ON DELETE CASCADE,
	"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE votes (
	"id" SERIAL PRIMARY KEY,
	"pain_id" INTEGER REFERENCES pains("id") ON DELETE CASCADE,
	"user_id" INTEGER REFERENCES users("id") ON DELETE CASCADE,
	"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	UNIQUE("pain_id", "user_id")
);

CREATE INDEX idx_pains_user_id ON pains("user_id");
CREATE INDEX idx_votes_pain_id ON votes("pain_id");
CREATE INDEX idx_votes_user_id ON votes("user_id");

CREATE TABLE "t_users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"login" VARCHAR(255) NOT NULL,
	"password" BYTEA NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "t_issue" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"created" DATE NOT NULL,
	"title" VARCHAR(255) NOT NULL,
	"description" TEXT NOT NULL,
	"active" BOOLEAN NOT NULL,
	"resolved" BOOLEAN NOT NULL,
	-- Отметка если проблема аналогична
	"repeated" INTEGER NOT NULL,
	PRIMARY KEY("id")
);COMMENT ON COLUMN t_issue.repeated IS 'Отметка если проблема аналогична';


CREATE TABLE "t_tags" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tag_name" CHAR(1) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "t_tag_issue" (
	"issue_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tag_id" INTEGER NOT NULL,
	PRIMARY KEY("issue_id", "tag_id")
);

ALTER TABLE "t_users"
ADD FOREIGN KEY("id") REFERENCES "t_issue"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "t_issue"
ADD FOREIGN KEY("id") REFERENCES "t_tag_issue"("issue_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "t_tags"
ADD FOREIGN KEY("id") REFERENCES "t_tag_issue"("tag_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;